assert a==15,"erreur"
print("Test rÃ©ussi")
